import fs from 'node:fs';
const document = JSON.parse(fs.readFileSync('documentation/api/openapi.json', 'utf8'));
fs.writeFileSync(
  'services/gateway/src/presentation/http/openapi-controller.ts',
  "// Generated by npm run api:sync from documentation/api/openapi.json.\nimport { Controller, Get } from '@nestjs/common';\nconst document = " +
    JSON.stringify(document, null, 2) +
    " as const;\n@Controller('api/v1/openapi.json')\nexport class OpenApiController {\n  @Get() get() {return document;}\n}\n",
);
